//
//  Settings.h
//  adhawk
//
//  Created by Daniel Cloud on 7/10/12.
//  Copyright (c) 2012 Sunlight Foundation. All rights reserved.
//


/*
#ifdef TESTING
    #define NSLog(__FORMAT__, ...) TFLog((@"%s [Line %d] " __FORMAT__), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
#endif
*/

FOUNDATION_EXPORT NSString* const TESTFLIGHT_TEAM_TOKEN;

FOUNDATION_EXPORT NSString* const ADHAWK_API_BASE_URL;

FOUNDATION_EXPORT NSString* const ADHAWK_APP_USER_AGENT;

FOUNDATION_EXPORT NSString* const ADHAWK_ABOUT_URL;

FOUNDATION_EXPORT NSString* const GIGYA_API_KEY;

FOUNDATION_EXPORT NSString* const FACEBOOOK_APP_ID;

FOUNDATION_EXPORT NSString* const TEST_FINGERPRINT;

FOUNDATION_EXPORT NSString* const TEST_SOCIAL_UPDATE;

FOUNDATION_EXPORT BOOL const TESTING;

FOUNDATION_EXPORT NSString* const ADHAWK_AUTH_USER;

FOUNDATION_EXPORT NSString* const ADHAWK_AUTH_PASSWORD;
